name: Apply Terraform and Create Kubernetes Resources

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="eks_role=${{ secrets.EKS_ROLE }}" \
          -var="mediamanagement_dbuser=${{ secrets.DB_USER }}" \
          -var="mediamanagement_dbpassword=${{ secrets.DB_PASSWORD }}"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="eks_role=${{ secrets.EKS_ROLE }}" \
          -var="mediamanagement_dbuser=${{ secrets.DB_USER }}" \
          -var="mediamanagement_dbpassword=${{ secrets.DB_PASSWORD }}"