name: 'Validate Terraform'

on:
  pull_request:

env:
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - id: init
      name: Terraform Init
      run: terraform init -backend=false

    - id: validate
      name: Terraform Validate
      run: terraform validate