name: Apply Terraform 

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  TF_INPUT: false
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - id: init
      name: Terraform Init
      run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_S3_BACKEND }}"

    - id: validate
      name: Terraform Validate
      run: terraform validate

    - id: plan
      name: Terraform Plan
      env: 
        TF_VAR_eks_role: ${{ secrets.EKS_ROLE }}
        TF_VAR_mediamanagement_dbuser: ${{ secrets.DB_USER }}
        TF_VAR_mediamanagement_dbpassword: ${{ secrets.DB_PASSWORD }}
      run: terraform plan 

    - id: apply
      if: github.ref == 'refs/heads/main'
      name: Terraform Apply
      env: 
        TF_VAR_eks_role: ${{ secrets.EKS_ROLE }}
        TF_VAR_mediamanagement_dbuser: ${{ secrets.DB_USER }}
        TF_VAR_mediamanagement_dbpassword: ${{ secrets.DB_PASSWORD }}
      run: terraform apply -auto-approve